abbr agi "ag --ignore-dir={'bootstrap*','node_modules','build','shopify-app'} --ignore={'*lock*',}"
abbr dcw "git dcw "
abbr fname "find . -name "
abbr fnmi "fnm env --use-on-cd --shell fish | source"
abbr finame "find . -iname "
abbr grepc "grep --color=always "
abbr ll "ls -l"
abbr ltr "ls -ltr"
abbr vim "vim -p"
abbr wezterm "/Applications/wezTerm.app/Contents/MacOS/wezterm "
